import { ModalProvider } from '@/providers/authModalProviders'
import './globals.css'
import type { Metadata } from 'next'
import { Noto_Serif } from 'next/font/google'
import { NextAuthProvider } from '@/providers/nextAuthProvider'
import { ToasterProvider } from '@/providers/toastProvider'

const inter =  Noto_Serif({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider/>
        <ToasterProvider/>
        <ModalProvider/>
        {children}
        </body>
    </html>
  )
}
