const TechLabelList = [
  "Web developer",
  "Software Engineer",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Mobile App Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "Cloud Architect",
  "Database Administrator",
  "Network Engineer",
  "Cybersecurity Analyst",
  "UX/UI Designer",
  "QA Engineer",
  "Product Manager",
  "Scrum Master",
  "Technical Writer",
  "Systems Analyst",
  "IT Consultant",
  "Blockchain Developer",
  "AI Researcher",
  "Robotics Engineer",
  "Game Developer",
  "IT Manager",
  "Tech Entrepreneur",
  "Software Architect",
  "System Administrator",
  "Tech Support Specialist",
  "Embedded Systems Engineer",
  "Firmware Engineer",
];
const Healthcare = [
  "Doctor",
  "Physician",
  "Surgeon",
  "Nurse Practitioner",
  "Registered Nurse",
  "Pharmacist",
  "Dentist",
  "Physical Therapist",
  "Occupational Therapist",
  "Speech-Language Pathologist",
  "Medical Technologist",
  "Radiologist",
  "Medical Researcher",
  "Psychiatrist",
  "Psychologist",
  "Social Worker",
  "Healthcare Administrator",
  "Health Informatics Specialist",
  "Clinical Informatics Analyst",
  "Nutritionist",
  "Paramedic",
  "Emergency Medical Technician (EMT)",
  "Medical Assistant",
  "Medical Lab Technician",
  "Orthopedic Surgeon",
  "Cardiologist",
  "Oncologist",
  "Pediatrician",
  "Obstetrician-Gynecologist (OB/GYN)",
  "Hospitalist",
  "Home Health Aide",
  "Patient Care Coordinator",
  "Clinical Nurse Specialist",
  "Midwife",
  "Medical Illustrator",
  "Medical Librarian"
];
const Finance = [
  "Financial Analyst",
    "Accountant",
    "CA",
    "Investment Banker",
    "Financial Advisor",
    "Actuary",
    "Risk Manager",
    "Insurance Underwriter",
    "Portfolio Manager",
    "Financial Planner",
    "Tax Consultant",
    "Economist",
    "Quantitative Analyst",
    "Credit Analyst",
    "Treasury Analyst",
    "Corporate Finance Manager",
    "Auditor",
    "Compliance Officer",
    "Hedge Fund Manager",
    "Private Equity Analyst",
    "Venture Capitalist",
    "Derivatives Trader",
    "Mergers and Acquisitions (M&A) Specialist",
    "Real Estate Analyst",
    "Bank Manager",
    "Financial Controller",
    "Financial Reporting Analyst",
    "Investment Analyst",
    "Credit Risk Analyst",
    "Chief Financial Officer (CFO)",
    "Financial Software Developer",
    "Financial Writer",
    "Financial Educator",
    "Budget Analyst"
];
const education = [
  "Teacher",
  "Professor",
  "School Counselor",
  "Educational Technologist",
  "Librarian",
  "Principal",
  "Curriculum Developer",
  "Special Education Teacher",
  "ESL Teacher",
  "Instructional Designer",
  "School Psychologist",
  "Admissions Counselor",
  "College Advisor",
  "Academic Dean",
  "Education Consultant",
  "Online Learning Specialist",
  "Montessori Teacher",
  "Homeschool Educator",
  "Early Childhood Educator",
  "Education Administrator",
  "Learning Support Specialist",
  "Foreign Language Teacher",
  "Technology Integration Specialist",
  "Adult Education Instructor",
  "GED Instructor",
  "Career Counselor",
  "Student Affairs Professional",
  "Education Policy Analyst",
  "Researcher in Education",
  "Education Blogger",
  "Educational Podcaster",
  "Public Speaker on Education",
  "Education Technology Trainer",
  "Education Writer",
  "Education Researcher",
  "Coaching Center Instructor",
  "Private Tutor",
  "Test Prep Instructor",
  "Subject-Specific Tutor",
  "Homework Help Tutor",
  "Study Skills Tutor",
  "Language Tutor",
  "Mathematics Tutor",
  "Science Tutor",
  "SAT/ACT Prep Instructor",
  "IELTS/TOEFL Tutor",
  "Exam Preparation Tutor",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Computer Science",
  "Economics",
  "Finance",
  "Business Administration",
  "History",
  "Political Science",
  "Sociology",
  "Psychology",
  "Philosophy",
  "Anthropology",
  "Geography",
  "Literature",
  "Languages",
  "Arts and Design",
  "Visual Arts",
  "Performing Arts",
  "Music",
  "Film Studies",
  "Communication",
  "Media Studies",
  "Health Sciences",
  "Nursing",
  "Medicine",
  "Public Health",
  "Environmental Studies",
  "Law",
  "Criminal Justice",
  "International Relations",
  "Social Work",
  "Education",
  "Religious Studies"

]
const student = [
  "Student",
  "Computer Science Student",
  "Engineering Student",
  "Business Administration Student",
  "Biology Student",
  "Psychology Student",
  "Art and Design Student",
  "Mathematics Student",
  "Physics Student",
  "Chemistry Student",
  "Environmental Science Student",
  "Political Science Student",
  "Economics Student",
  "History Student",
  "Literature Student",
  "Language and Linguistics Student",
  "Health Sciences Student",
  "Social Work Student",
  "Education Student",
  "Law Student",
  "Media Studies Student",
  "Information Technology Student",
  "Finance Student",
  "Marketing Student",
  "Communication Student",
  "Data Science Student",
  "Pre-Med Student",
  "Pre-Law Student",
  "Philosophy Student",
  "Sociology Student",
  "Anthropology Student",
  "Architecture Student",
  "Public Health Student",
  "International Relations Student",
  "Urban Planning Student",
  "Nursing Student",
  "Physics Student",
  "Chemical Engineering Student",
  "Mechanical Engineering Student",
  "Electrical Engineering Student",
  "Civil Engineering Student",
  "Astronomy Student",
  "Statistics Student",
  "Actuarial Science Student",
  "Environmental Engineering Student",
  "Robotics Engineering Student",
  "Civil Services Aspirant",
  "School student"

];
const Business = [
  "Business Analyst",
  "Financial Analyst",
  "Accountant",
  "Marketing Manager",
  "Sales Representative",
  "Human Resources Specialist",
  "Project Manager",
  "Entrepreneur",
  "Management Consultant",
  "Operations Manager",
  "Investment Banker",
  "Financial Advisor",
  "Risk Manager",
  "Corporate Lawyer",
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Retail Manager",
  "Brand Strategist",
  "Market Research Analyst",
  "E-commerce Manager",
  "Social Media Manager",
  "Public Relations Specialist",
  "Leadership Coach",
  "Business Communication Specialist",
  "Strategic Planner",
  "Financial Controller",
  "Investment Manager",
  "Corporate Finance Manager",
  "Business Development Manager",
  "Organizational Development Specialist",
  "Change Management Consultant",
  "International Business Consultant",
  "Sustainable Business Consultant",
  "Quality Assurance Manager",
  "Management Information Systems Manager",
  "Data Scientist for Business",
  "Business Intelligence Analyst",
  "CEO",
  "CFO",
  "CMO",
  "COO",
  "CIO",
  "CHRO",
  "CSR Manager",
  "Business Innovation Specialist"
];
const Engineering = [
  "Mechanical Engineer",
    "Electrical Engineer",
    "Civil Engineer",
    "Chemical Engineer",
    "Aerospace Engineer",
    "Computer Engineer",
    "Software Engineer",
    "Biomedical Engineer",
    "Environmental Engineer",
    "Structural Engineer",
    "Industrial Engineer",
    "Automotive Engineer",
    "Materials Engineer",
    "Petroleum Engineer",
    "Electronics Engineer",
    "Robotics Engineer",
    "Nuclear Engineer",
    "Geotechnical Engineer",
    "Water Resources Engineer",
    "Power Systems Engineer",
    "Process Engineer",
    "Telecommunications Engineer",
    "Control Systems Engineer",
    "Network Engineer",
    "Quality Assurance Engineer",
    "Manufacturing Engineer",
    "Mining Engineer",
    "Ocean Engineer",
    "Railway Engineer",
    "Safety Engineer",
    "Systems Engineer",
    "Renewable Energy Engineer",
    "Instrumentation Engineer",
    "Fire Protection Engineer",
    "Biochemical Engineer",
    "Marine Engineer",
    "HVAC Engineer",
    "Acoustic Engineer",
    "Reliability Engineer",
    "Photonics Engineer",
    "Biomechanical Engineer",
    "Avionics Engineer",
    "Traffic Engineer",
    "Water Quality Engineer",
    "Naval Architect",
    "Facilities Engineer",
    "Audio Engineer",
    "Human Factors Engineer"

];
const ArtsandDesign = [
  "Graphic Designer",
  "UI/UX Designer",
  "Illustrator",
  "Animator",
  "Web Designer",
  "Game Designer",
  "Fashion Designer",
  "Interior Designer",
  "Architect",
  "Industrial Designer",
  "Product Designer",
  "Motion Graphics Designer",
  "Art Director",
  "Creative Director",
  "Photographer",
  "Videographer",
  "Digital Artist",
  "Fine Artist",
  "Printmaker",
  "Textile Designer",
  "Jewelry Designer",
  "Package Designer",
  "User Interface Artist",
  "Environmental Designer",
  "Exhibition Designer",
  "Set Designer",
  "Visual Development Artist",
  "Character Designer",
  "Storyboard Artist",
  "Makeup Artist",
  "Tattoo Artist",
  "Comic Book Artist",
  "3D Modeler",
  "Event Planner",
  "Floral Designer",
  "Ceramic Artist",
  "Glass Artist",
  "Book Cover Designer",
  "Brand Identity Designer",
  "Typography Designer",
  "Color Consultant",
  "Creative Writer",
  "Curator",
  "Gallery Owner",
  "Art Therapist",
  "Museum Educator",
  "Art Historian",
  "Furniture Designer",
  "Sculptor",
  "Cartoonist",
  "Visual Merchandiser"
];
const Legal = [
  "Lawyer",
    "Attorney",
    "Legal Counsel",
    "Legal Analyst",
    "Legal Consultant",
    "Judge",
    "Legal Researcher",
    "Paralegal",
    "Legal Secretary",
    "Corporate Counsel",
    "Criminal Defense Attorney",
    "Prosecutor",
    "Family Law Attorney",
    "Immigration Attorney",
    "Estate Planning Attorney",
    "Intellectual Property Attorney",
    "Environmental Attorney",
    "Healthcare Attorney",
    "Labor and Employment Attorney",
    "Bankruptcy Attorney",
    "Tax Attorney",
    "Civil Rights Attorney",
    "Real Estate Attorney",
    "Contract Attorney",
    "Government Attorney",
    "Legal Aid Lawyer",
    "Public Defender",
    "Private Practice Attorney",
    "Human Rights Lawyer",
    "Entertainment Lawyer",
    "International Lawyer",
    "Litigation Attorney",
    "Legal Compliance Officer",
    "Legal Operations Manager",
    "Legal Technology Specialist",
    "Legal Marketing Specialist",
    "Legal Educator",
    "Legal Writer",
    "Legal Translator",
    "Arbitrator",
    "Mediator",
    "Legal Investigator",
    "Legal Nurse Consultant",
    "Legal Administrator",
    "Legal Executive Assistant",
    "Legal Receptionist",
    "Legal Assistant",
    "Legal Secretary",
    "Court Reporter",
    "Bailiff"
];
const Science = [
  "Scientist",
    "Biologist",
    "Chemist",
    "Physicist",
    "Astronomer",
    "Geologist",
    "Ecologist",
    "Environmental Scientist",
    "Botanist",
    "Zoologist",
    "Microbiologist",
    "Geneticist",
    "Neuroscientist",
    "Immunologist",
    "Epidemiologist",
    "Biophysicist",
    "Oceanographer",
    "Astrophysicist",
    "Materials Scientist",
    "Nuclear Physicist",
    "Climatologist",
    "Meteorologist",
    "Seismologist",
    "Forensic Scientist",
    "Data Scientist",
    "Research Scientist",
    "Clinical Researcher",
    "Science Educator",
    "Science Communicator",
    "Science Journalist",
    "Lab Technician",
    "Analytical Chemist",
    "Quality Control Analyst",
    "Medical Researcher",
    "Pharmaceutical Scientist",
    "Food Scientist",
    "Wildlife Biologist",
    "Conservation Scientist",
    "Science Illustrator",
    "Science Photographer",
    "Astrobiologist",
    "Science Policy Analyst",
    "Biomedical Engineer",
    "Science Librarian",
    "Science Outreach Coordinator",
    "Field Biologist",
    "Particle Physicist",
    "Genomic Scientist",
    "Bioinformatics Specialist",
    "Science Curriculum Developer",
    "Educational Researcher"
];
const Other = [
  "Freelancer",
  "Consultant",
  "Project Manager",
  "Customer Support Representative",
  "Social Media Manager",
  "Content Creator",
  "Blogger",
  "Copywriter",
  "Technical Writer",
  "Journalist",
  "Editor",
  "Novelist",
  "Poet",
  "Screenwriter",
  "Ghostwriter",
  "Content Strategist",
  "Public Relations Specialist",
  "Marketing Specialist",
  "Digital Marketer",
  "SEO Specialist",
  "Graphic Designer",
  "Web Developer",
  "App Developer",
  "Game Developer",
  "Software Architect",
  "IT Specialist",
  "Systems Administrator",
  "Network Administrator",
  "Database Administrator",
  "Cybersecurity Analyst",
  "Ethical Hacker",
  "Data Analyst",
  "Data Scientist",
  "Statistician",
  "Quantitative Analyst",
  "Financial Planner",
  "Investment Advisor",
  "Real Estate Agent",
  "Insurance Agent",
  "Tax Consultant",
  "Personal Trainer",
  "Nutritionist",
  "Yoga Instructor",
  "Life Coach",
  "Therapist",
  "Psychiatrist",
  "Medical Doctor",
  "Nurse",
  "Paramedic",
  "Police Officer",
  "Firefighter",
  "Emergency Medical Technician (EMT)",
  "Chef",
  "Baker",
  "Caterer",
  "Event Planner",
  "Travel Blogger",
  "Photographer",
  "Videographer",
  "Podcaster",
  "YouTuber",
  "Twitch Streamer",
  "Influencer",
  "Model",
  "Actor",
  "Musician",
  "Dancer",
  "Artist",
  "Athlete",
  "Coach",
  "Personal Assistant",
  "Virtual Assistant",
  "Executive Assistant",
  "Administrative Assistant",
  "Secretary"
];

export const LabelList = [{ title: "Tech", list: TechLabelList },{title:"Healthcare", list:Healthcare},{title:"Finance", list:Finance},{title:"Education", list:education},{title:"Student", list:student},{title:"Business", list:Business},{title:"Engineer", list:Engineering},{title:"Arts and Design", list:ArtsandDesign},{title:"Legal", list:Legal},{title:"Science", list:Science},{title:"Other", list:Other}];
